export const SWAGGER_API_ROOT = 'api/docs';
export const SWAGGER_API_NAME = 'BOILERPLATE NEST/PRISMA API';
export const SWAGGER_API_DESCRIPTION =
  'BOILERPLATE NEST/PRISMA API DESCRIPTION';
export const SWAGGER_API_CURRENT_VERSION = '1.0';
